### ISSUE TITLE
No definition for 'mesh' port input

### ISSUE THREAD

**Issue by Tehsurfer** [mahyar-osn/mapclientplugins.parametricfittingstep#1]
When creating a Mapclient workflow to try and run the plugin, I cannot figure out how to define  the 'mesh' input for the step. 

In [step.py]( https://github.com/mahyar-osn/mapclientplugins.parametricfittingstep/blob/master/mapclientplugins/parametricfittingstep/step.py) we have the following snippet:

```python 
self.addPort(('http://physiomeproject.org/workflow/1.0/rdf-schema#port',
                      'http://physiomeproject.org/workflow/1.0/rdf-schema#uses',
                      'http://physiomeproject.org/workflow/1.0/rdf-schema#mesh'))
```

**Comment by mahyar-osn** [comment]
You can create an instance attribute in the constructor e.g. `self._mesh = None` then create a method like below: 

```
    def setPortData(self, index, dataIn):
        """
        Add your code here that will set the appropriate objects for this step.
        The index is the index of the port in the port list.  If there is only one
        uses port for this step then the index can be ignored.

        :param index: Index of the port to return.
        :param dataIn: The data to set for the port at the given index.
        """
        self._mesh = dataIn
```

You could then use this instance variable anywhere else in your code. 

Let me know if there's anything else. Hope that helps.

**Comment by Tehsurfer** [comment]
Thanks Mahyar that does make sense I will try that. 

One more question, does parametricfittingstep require a link to another step or does it run by having the mayhar/meshgeneratorstep in the same plugins folder?  I currently have the standard workflow set up (shown below) with parametricfittingstep in the plugins folder being called via python imports in mayhar/meshgeneratorstep.

![workflow](https://user-images.githubusercontent.com/37255664/46588157-b6f25a80-caf3-11e8-9dc7-f53bfcf61d90.png)

**Comment by mahyar-osn** [comment]
The current fitting step requires image source step and the mesh generator step as you have shown above. Only you need to connect the mesh generator step to the fitting step as shown below. You don't have to the file sink step at this stage. 
![selection_261](https://user-images.githubusercontent.com/6082104/46692553-153e4b00-cc64-11e8-82c4-03533e130071.png)

**Comment by Tehsurfer** [comment]
Thanks Mayhar, I completely missed the fact that you can also use the given config folder as a workflow. I'm using that one now and it's working well.
