### ISSUE TITLE
Error: No Landmarks during fitting

### ISSUE THREAD

**Issue by Tehsurfer** [mahyar-osn/mapclientplugins.parametricfittingstep#2]
When trying to do a rigid fitting of the mesh I'm getting the following error:

```
Rigid Fitting...
Traceback (most recent call last):
  File "c:\users\jkho021\projects\sparc\plugins\mapclientplugins.meshgeneratorstep\mapclientplugins\meshgeneratorstep\view\meshgeneratorwidget.py", line 408, in _calculateRigidTransform
    _, transformation = self._rigidTransform(self.fiducial_marker_positions, node_value_array)
  File "c:\users\jkho021\projects\sparc\plugins\mapclientplugins.meshgeneratorstep\mapclientplugins\meshgeneratorstep\view\meshgeneratorwidget.py", line 574, in _rigidTransform
    fitting = RigidFitting(**{'X': landmark, 'Y': node})
  File "c:\users\jkho021\projects\sparc\plugins\mapclientplugins.parametricfittingstep\mapclientplugins\parametricfittingstep\core\RigidFitting.py", line 7, in __init__
    super(RigidFitting, self).__init__(*args, **kwargs)
  File "c:\users\jkho021\projects\sparc\plugins\mapclientplugins.parametricfittingstep\mapclientplugins\parametricfittingstep\core\Optimization.py", line 27, in __init__
    raise ValueError("Fiducial landmarks must be a numpy array with at least 2 dimensions.")
ValueError: Fiducial landmarks must be a numpy array with at least 2 dimensions.
```
in [meshgeneratorwidget.py:line 414](https://github.com/mahyar-osn/mapclientplugins.meshgeneratorstep/blob/e7bec3dea5855d194f160de4dd96c9ab276bef15/mapclientplugins/meshgeneratorstep/view/meshgeneratorwidget.py#L414-L420) we have:

```python
 if self.fiducial_marker_positions is not None:
            self.fiducial_marker_positions = None
            self.fiducial_marker_positions = np.asarray(self._fiducial_marker_model.getNodeLocation())

        """ computing rigid transformation parameters 1 """
        _, transformation = self._rigidTransform(self.fiducial_marker_positions, node_value_array)
        ridid_scale = transformation.s
```

I cannot find anywhere in the file where `self.fiducial_marker_positions` is defined, so it always gets passed to `self._rigidTransform` as `NoneType`.

**Comment by mahyar-osn** [comment]
`self.fiducial_marker_positions` is defined when you define a landmark on the image plane within the GUI. See the screenshot attached. On the left side in the Control Panel widget, there is a field "Fiducial markers" and a drop-down menu "Labels". You need to select "1" and then press down on Ctrl key and click on the image (for example the apex as in the screenshot attached). A blue landmark is defined. Next, you select "2" and define the second landmark (see the "fiducial_landmarks_example.png" in the repo for an example of a complete landmarking) and so on. 

![selection_262](https://user-images.githubusercontent.com/6082104/46771902-08982080-cd52-11e8-9443-e68e1042d31f.png)

Hope that helps!

**Comment by Tehsurfer** [comment]
Oh yeah sorry I should have shared my fiducial markers, good to cover the most basic solutions first: 
![image](https://user-images.githubusercontent.com/37255664/46772174-7ccbb900-ccab-11e8-96cd-94bb554d96df.png)

I'm actually having a problem where I can't figure out where in the project (mayhar/meshgeneratorstep an parametricfittingstep) `self.fiducial_marker_positions` is assigned a value. 

I've tried searching `self.fiducial_marker_positions` in [meshgeneratorwidget.py](https://github.com/mahyar-osn/mapclientplugins.meshgeneratorstep/blob/master/mapclientplugins/meshgeneratorstep/view/meshgeneratorwidget.py) and looked for it imported into any of the other files but haven't found anything.

**Comment by mahyar-osn** [comment]
I actually noticed something in the above code snippet. The code should be: 

` if self.fiducial_marker_positions is not None:
            self.fiducial_marker_positions = None

 self.fiducial_marker_positions = np.asarray(self._fiducial_marker_model.getNodeLocation())`

Now, `self.fiducial_marker_positions` is defined.

**Comment by Tehsurfer** [comment]
Ah I see that does make sense actually now that I think about it. Thanks Mayhar 😄

**Comment by Tehsurfer** [comment]
Niiice got it working

![image](https://user-images.githubusercontent.com/37255664/46772925-632c7080-ccaf-11e8-9b4f-ff0b2a56024b.png)

**Comment by mahyar-osn** [comment]
Awesome!
